# Generated by Django 4.2 on 2023-04-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIData',
        ),
    ]
