# Generated by Django 4.2 on 2023-04-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recipes', '0002_delete_apidata'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_ing', models.CharField(max_length=10000)),
            ],
        ),
    ]
